using System.Collections.Generic;
using UnityEngine;

namespace Kanikama.Core.Editor
{
    // asset data generated by unity lightmapper
    public sealed class BakedLightmap
    {
        public LightmapType Type { get; }
        public Texture2D Texture { get; }
        public string Path { get; }
        public int Index { get; }

        public BakedLightmap(LightmapType type, Texture2D texture, string path, int index)
        {
            Type = type;
            Texture = texture;
            Path = path;
            Index = index;
        }
    }

    public sealed class BakedLightingAssetCollection
    {
        public List<BakedLightmap> Lightmaps = new List<BakedLightmap>();
        public List<BakedLightmap> DirectionalLightmaps = new List<BakedLightmap>();
        public List<BakedLightmap> ShadowMasks = new List<BakedLightmap>();
    }

    public enum LightmapType
    {
        Color = 0,
        Directional = 1,
        ShadowMask = 2,
    }
}
