name: Build Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

env:
  project_name: "Kanikama"
  package_name0: "net.shivaduke28.kanikama"
  package_name1: "net.shivaduke28.kanikama.bakery"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set tag
        run: echo "release_version=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: "Create zip0"
        id: "create-zip-0"
        uses: ./.github/composite/create-zip
        with:
          project_name: ${{ env.project_name }}
          package_name: ${{ env.package_name0 }}
      - name: "Create zip1"
        id: "create-zip-1"
        uses: ./.github/composite/create-zip
        with:
          project_name: ${{ env.project_name }}
          package_name: ${{ env.package_name1 }}

      - name: Make release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        with:
          tag_name: ${{ env.release_version }}
          files: |
            ${{ steps.create-zip-0.outputs.zip_file }}
            ${{ steps.create-zip-1.outputs.zip_file }}
